<?php
define("RESPONSE_SUCCESS", 100);
define("RESPONSE_FAILURE", 900);
define("STATUS_CODE_OK", "OK");
define("STATUS_CODE_ERROR", "ERROR");

define("MSG_ACCESS_GRANTED", "ACCESS GRANTED");
define("MSG_ACCESS_DENIED", "ACCESS DENIED");
define("MSG_LOGOUT", "LOGOUT SYSTEM");